version: '3.9'
services:
  node_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=arman
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arman
      - MONGO_INITDB_ROOT_PASSWORD=password